/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    'feedback-record': FeedbackRecord;
    rooms: Room;
  };
  globals: {};
}
export interface FeedbackRecord {
  id: string;
  email?: string | null;
  status?: ('0' | '1') | null;
  type: '1' | '2' | '3';
  content: string;
  replyContent?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Room {
  id: string;
  roomId: string;
  houseOwnerId: string;
  hash: string;
  iv: string;
  updatedAt: string;
  createdAt: string;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
